name: Lint and check format

on: 
  push:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    name: Run biome checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run biome
        run: npm run check
